"""
Expanding is the task of taking a short piece of text and having the large language model generate a longer piece of text.

example : Generating personalized emails based on customer reviews.

Note:

It is important to use the capabilities of the language models responsibly and transparently.
Such as acknowledging that a text was generated by AI as shown in the next card.
"""

import openai
from dotenv import load_dotenv


load_dotenv()

client = openai.OpenAI()

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0
    )
    return response.choices[0].message.content

sentiment = "funny"
snippet = "A dog and cat are playing"


prompt = f"""
You are a story writer.
Your task is to write a story based on a snippet that is provided.
Given the snippet delimited by ```, The story can be funny or sad based on the sentiment provided. The story should be no more than 50 words.
snippet: ```{snippet}```
sentiment: {sentiment}
"""

response = get_completion(prompt)
print(response)